# Generated by Django 6.0.1 on 2026-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100, unique=True)),
                ('Product_Price', models.FloatField()),
                ('Product_Description', models.TextField()),
                ('Product_Image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
