# Generated by Django 6.0.1 on 2026-02-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100)),
                ('ServiceDescription', models.TextField()),
                ('ServiceImage', models.ImageField(upload_to='Lux_services')),
            ],
        ),
    ]
