# Generated by Django 6.0.2 on 2026-02-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_cartdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartDb',
        ),
    ]
