# Generated by Django 6.0.2 on 2026-02-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_userdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cart_Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Cart_ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Cart_Quantity', models.IntegerField(blank=True, null=True)),
                ('Cart_Price', models.FloatField(blank=True, null=True)),
                ('Cart_TotalPrice', models.FloatField(blank=True, null=True)),
                ('Cart_ProductImage', models.ImageField(blank=True, null=True, upload_to='Cart_Image')),
            ],
        ),
    ]
